name: Run Python Script Every 1. Hours

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Configure git credentials
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests charset-normalizer urllib3 certifi idna
      - name: Run script with retry
        run: |
          max_retries=3
          retry_count=0
          while [ $retry_count -lt $max_retries ]; do
            if python excuseapinew.py; then
              break
            else
              retry_count=$((retry_count + 1))
              if [ $retry_count -lt $max_retries ]; then
                echo "Attempt $retry_count failed. Waiting 60 seconds before retry..."
                sleep 60
              fi
            fi
          done
          if [ $retry_count -eq $max_retries ]; then
            echo "All retry attempts failed"
            exit 1
          fi
