name: Run Python Script Randomly
on:
  schedule:
    - cron: "*/3 * * * *" # Runs every 3 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Configure git credentials
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests charset-normalizer urllib3 certifi idna urllib3
      - name: Add random delay
        run: |
          sleep $((RANDOM % 60))  # Random delay between 0-59 seconds
      - name: Run script with retry
        run: |
          max_retries=3
          retry_count=0
          while [ $retry_count -lt $max_retries ]; do
            if python excuseapinew.py; then
              break
            else
              retry_count=$((retry_count + 1))
              if [ $retry_count -lt $max_retries ]; then
                random_wait=$((30 + RANDOM % 60))  # Random wait between 30-89 seconds
                echo "Attempt $retry_count failed. Waiting $random_wait seconds before retry..."
                sleep $random_wait
              fi
            fi
          done
          if [ $retry_count -eq $max_retries ]; then
            echo "All retry attempts failed"
            exit 1
          fi
